[package]
name = "rust_api"
version = "0.1.0"
edition = "2024"
default-run = "rust_api"

[dependencies]
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
validator = { version = "0.21.0", features = ["derive"] }

sea-orm = { version = "2.0.0", features = [
    "sqlx-mysql",
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
] }

dotenv = "0.15"

chrono-tz = "0.10.4"

jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }

chrono="0.4.45"

base64 = "0.23.0"

sha2 = "0.11.0"
anyhow = "1.0.104"
users = "0.11.0"

fake = { version = "5.1.0", features = ["derive"] }
rand = "0.10.2"



